# Generated by Django 3.0.7 on 2020-07-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partymenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=10)),
                ('item', models.CharField(max_length=100)),
                ('small_tray', models.IntegerField()),
                ('large_tray', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('up_date', models.DateTimeField()),
            ],
        ),
    ]
