# Generated by Django 3.0.7 on 2020-07-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhojan', '0002_auto_20200716_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymenu',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
